export const EXCHANGE_LIST_REQUEST = 'EXCHANGE_LIST_REQUEST';
export const EXCHANGE_LIST_SUCCESS = 'EXCHANGE_LIST_SUCCESS';
export const EXCHANGE_LIST_FAIL = 'EXCHANGE_LIST_FAIL';

export const EXCHANGE_ADD_REQUEST = 'EXCHANGE_ADD_REQUEST';
export const EXCHANGE_ADD_SUCCESS = 'EXCHANGE_ADD_SUCCESS';
export const EXCHANGE_ADD_FAIL = 'EXCHANGE_ADD_FAIL';

export const EXCHANGE_EDIT_REQUEST = 'EXCHANGE_EDIT_REQUEST';
export const EXCHANGE_EDIT_SUCCESS = 'EXCHANGE_EDIT_SUCCESS';
export const EXCHANGE_EDIT_FAIL = 'EXCHANGE_EDIT_FAIL';

export const EXCHANGE_DELETE_REQUEST = 'EXCHANGE_DELETE_REQUEST';
export const EXCHANGE_DELETE_SUCCESS = 'EXCHANGE_DELETE_SUCCESS';
export const EXCHANGE_DELETE_FAIL = 'EXCHANGE_DELETE_FAIL';