export const IPO_LIST_REQUEST = 'IPO_LIST_REQUEST';
export const IPO_LIST_SUCCESS = 'IPO_LIST_SUCCESS';
export const IPO_LIST_FAIL = 'IPO_LIST_FAIL';

export const IPO_ADD_REQUEST = 'IPO_ADD_REQUEST';
export const IPO_ADD_SUCCESS = 'IPO_ADD_SUCCESS';
export const IPO_ADD_FAIL = 'IPO_ADD_FAIL';

export const IPO_EDIT_REQUEST = 'IPO_EDIT_REQUEST';
export const IPO_EDIT_SUCCESS = 'IPO_EDIT_SUCCESS';
export const IPO_EDIT_FAIL = 'IPO_EDIT_FAIL';

export const IPO_DELETE_REQUEST = 'IPO_DELETE_REQUEST';
export const IPO_DELETE_SUCCESS = 'IPO_DELETE_SUCCESS';
export const IPO_DELETE_FAIL = 'IPO_DELETE_FAIL';