export const SECTOR_LIST_REQUEST = 'SECTOR_LIST_REQUEST';
export const SECTOR_LIST_SUCCESS = 'SECTOR_LIST_SUCCESS';
export const SECTOR_LIST_FAIL = 'SECTOR_LIST_FAIL';

export const SECTOR_ADD_REQUEST = 'SECTOR_ADD_REQUEST';
export const SECTOR_ADD_SUCCESS = 'SECTOR_ADD_SUCCESS';
export const SECTOR_ADD_FAIL = 'SECTOR_ADD_FAIL';

export const SECTOR_EDIT_REQUEST = 'SECTOR_EDIT_REQUEST';
export const SECTOR_EDIT_SUCCESS = 'SECTOR_EDIT_SUCCESS';
export const SECTOR_EDIT_FAIL = 'SECTOR_EDIT_FAIL';

export const SECTOR_DELETE_REQUEST = 'SECTOR_DELETE_REQUEST';
export const SECTOR_DELETE_SUCCESS = 'SECTOR_DELETE_SUCCESS';
export const SECTOR_DELETE_FAIL = 'SECTOR_DELETE_FAIL';